### ISSUE TITLE
unable to run this example

### ISSUE THREAD

**Issue by nsankar90** [neuronetio/angular-gantt-schedule-timeline-calendar-example#2]
could you please check and update the following

Thanks

**Comment by neuronetio** [comment]
which❓

**Comment by neuronetio** [comment]
aha this :D ok

**Comment by nsankar90** [comment]
My project was running on top of angular 8.3.14

May I know the which is the stable version that supports it?

**Comment by neuronetio** [comment]
any version should work- but wait a while and I will update this example with the lastest gantt version

**Comment by nsankar90** [comment]
Thank you very much Rafeal

The complex example was really awesome!

**Comment by neuronetio** [comment]
ok, you can try now (pull changes)

**Comment by nsankar90** [comment]
when I upgrade it from 3.10.1 to 3.33.6

I found the below issue
```
ERROR in node_modules/gantt-schedule-timeline-calendar/dist/api/api.d.ts:7:13 - error TS1005: '=' expected.

7 import type DeepState from 'deep-state-observer';
              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/api.d.ts:7:23 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                        ~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/api.d.ts:7:28 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                             ~~~~~~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/api.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DataChartTime, Row, Item, Vido, Items, Rows, GridCell, GridRows, GridRow, GridCells, DataItems, ItemData, ItemDataUpdate, ColumnData, RowData, RowsData, ItemDataPosition, DataChartTimeLevels, DataScrollVertical, DataScrollHorizontal, ItemRowMap, ChartTimeDates } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/api/api.d.ts:8:283 - error TS1005: ';' expected.

8 import type { DataChartTime, Row, Item, Vido, Items, Rows, GridCell, GridRows, GridRow, GridCells, DataItems, ItemData, ItemDataUpdate, ColumnData, RowData, RowsData, ItemDataPosition, DataChartTimeLevels, DataScrollVertical, DataScrollHorizontal, ItemRowMap, ChartTimeDates } from '../gstc';
                                                                                                                                                                                                                                                                                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/public.d.ts:3:13 - error TS1005: '=' expected.

3 import type { Config, Locale, Period } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/api/public.d.ts:3:45 - error TS1005: ';' expected.

3 import type { Config, Locale, Period } from '../gstc';
                                              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:7:13 - error TS1005: '=' expected.

7 import type { Dayjs } from 'dayjs';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:7:28 - error TS1005: ';' expected.

7 import type { Dayjs } from 'dayjs';
                             ~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DataChartTime, DataChartTimeLevelDate, ChartTimeDate, Period, ChartCalendarLevel, ChartCalendarLevelFormat } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:8:129 - error TS1005: ';' expected.

8 import type { DataChartTime, DataChartTimeLevelDate, ChartTimeDate, Period, ChartCalendarLevel, ChartCalendarLevelFormat } from '../gstc';
                                                                                                                                  ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:9:13 - error TS1005: '=' expected.

9 import type DeepState from 'deep-state-observer';
              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:9:23 - error TS1005: ';' expected.

9 import type DeepState from 'deep-state-observer';
                        ~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:9:28 - error TS1005: ';' expected.

9 import type DeepState from 'deep-state-observer';
                             ~~~~~~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:10:13 - error TS1005: '=' expected.

10 import type { Api } from './api';
               ~
node_modules/gantt-schedule-timeline-calendar/dist/api/time.d.ts:10:26 - error TS1005: ';' expected.

10 import type { Api } from './api';
                            ~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/gstc.d.ts:7:13 - error TS1005: '=' expected.

7 import type { vido } from '@neuronet.io/vido';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/gstc.d.ts:7:27 - error TS1005: ';' expected.

7 import type { vido } from '@neuronet.io/vido';
                            ~~~~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/highlight-weekends.esm.min.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/highlight-weekends.esm.min.d.ts:6:27 - error TS1005: ';' expected.

6 import type { Vido } from '../gstc';
                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido, Item, DataChartTime, ItemData, DataItems, DataScrollVertical, DataScrollHorizontal } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:6:111 - error TS1005: ';' expected.

6 import type { Vido, Item, DataChartTime, ItemData, DataItems, DataScrollVertical, DataScrollHorizontal } from '../gstc';
                                                                                                                ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:7:13 - error TS1005: '=' expected.

7 import type DeepState from 'deep-state-observer';
              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:7:23 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                        ~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:7:28 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                             ~~~~~~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:8:13 - error TS1005: '=' expected.

8 import type { Dayjs } from 'dayjs';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-movement.esm.min.d.ts:8:28 - error TS1005: ';' expected.

8 import type { Dayjs } from 'dayjs';
                             ~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido, htmlResult, Item, DataChartTime, DataItems, DataScrollHorizontal } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:6:93 - error TS1005: ';' expected.

6 import type { Vido, htmlResult, Item, DataChartTime, DataItems, DataScrollHorizontal } from '../gstc';
                                                                                              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:7:13 - error TS1005: '=' expected.

7 import type DeepState from 'deep-state-observer';
              ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:7:23 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                        ~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:7:28 - error TS1005: ';' expected.

7 import type DeepState from 'deep-state-observer';
                             ~~~~~~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:8:13 - error TS1005: '=' expected.

8 import type { Dayjs } from 'dayjs';
              ~
96mnode_modules/gantt-schedule-timeline-calendar/dist/plugins/item-resizing.esm.min.d.ts:8:28 - error TS1005: ';' expected.

8 import type { Dayjs } from 'dayjs';
                             ~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/progress-bar.esm.min.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/progress-bar.esm.min.d.ts:6:27 - error TS1005: ';' expected.

6 import type { Vido } from '../gstc';
                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/selection.esm.min.d.ts:7:13 - error TS1005: '=' expected.

7 import type { Item, GridCell, Vido } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/selection.esm.min.d.ts:7:43 - error TS1005: ';' expected.

7 import type { Item, GridCell, Vido } from '../gstc';
                                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/timeline-pointer.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/timeline-pointer.d.ts:6:27 - error TS1005: ';' expected.

6 import type { Vido } from '../gstc';
                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/timeline-pointer.esm.min.d.ts:6:13 - error TS1005: '=' expected.

6 import type { Vido } from '../gstc';
              ~
node_modules/gantt-schedule-timeline-calendar/dist/plugins/timeline-pointer.esm.min.d.ts:6:27 - error TS1005: ';' expected.

6 import type { Vido } from '../gstc';
                            ~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/async-append.d.ts:38:1 - error TS1128: Declaration or statement expected.

38 export type { AsyncAppendDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/async-append.d.ts:38:13 - error TS1005: ';' expected.

38 export type { AsyncAppendDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/cache.d.ts:34:1 - error TS1128: Declaration or statement expected.

34 export type { CacheDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/cache.d.ts:34:13 - error TS1005: ';' expected.

34 export type { CacheDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/class-map.d.ts:44:1 - error TS1128: Declaration or statement expected.

44 export type { ClassMapDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/class-map.d.ts:44:13 - error TS1005: ';' expected.

44 export type { ClassMapDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/guard.d.ts:59:1 - error TS1128: Declaration or statement expected.

59 export type { GuardDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/guard.d.ts:59:13 - error TS1005: ';' expected.

59 export type { GuardDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/live.d.ts:42:1 - error TS1128: Declaration or statement expected.

42 export type { LiveDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/live.d.ts:42:13 - error TS1005: ';' expected.

42 export type { LiveDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/ref.d.ts:22:1 - error TS1128: Declaration or statement expected.

22 export type { Ref };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/ref.d.ts:22:13 - error TS1005: ';' expected.

22 export type { Ref };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/ref.d.ts:65:1 - error TS1128: Declaration or statement expected.

65 export type { RefDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/ref.d.ts:65:13 - error TS1005: ';' expected.

65 export type { RefDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/repeat.d.ts:63:1 - error TS1128: Declaration or statement expected.

63 export type { RepeatDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/repeat.d.ts:63:13 - error TS1005: ';' expected.

63 export type { RepeatDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/style-map.d.ts:47:1 - error TS1128: Declaration or statement expected.

47 export type { StyleMapDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/style-map.d.ts:47:13 - error TS1005: ';' expected.

47 export type { StyleMapDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/template-content.d.ts:25:1 - error TS1128: Declaration or statement expected.

25 export type { TemplateContentDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/template-content.d.ts:25:13 - error TS1005: ';' expected.

25 export type { TemplateContentDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/unsafe-svg.d.ts:26:1 - error TS1128: Declaration or statement expected.

26 export type { UnsafeSVGDirective };
   ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/directives/unsafe-svg.d.ts:26:13 - error TS1005: ';' expected.

26 export type { UnsafeSVGDirective };
               ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:7:13 - error TS1005: '=' expected.

7 import type { Directive } from './directive.js';
              ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:7:32 - error TS1005: ';' expected.

7 import type { Directive } from './directive.js';
                                 ~~~~~~~~~~~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:395:1 - error TS1128: Declaration or statement expected.

395 export type { ChildPart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:395:13 - error TS1005: ';' expected.

395 export type { ChildPart };
                ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:461:1 - error TS1128: Declaration or statement expected.

461 export type { AttributePart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:461:13 - error TS1005: ';' expected.

461 export type { AttributePart };
                ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:478:1 - error TS1128: Declaration or statement expected.

478 export type { PropertyPart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:478:13 - error TS1005: [0m';' expected.

478 export type { PropertyPart };
                ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:482:1 - error TS1128: Declaration or statement expected.

482 export type { BooleanAttributePart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:482:13 - error TS1005: ';' expected.

482 export type { BooleanAttributePart };
                ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:497:1 - error TS1128: Declaration or statement expected.

497 export type { EventPart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:497:13 - error TS1005: ';' expected.

497 export type { EventPart };
                ~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:503:1 - error TS1128: Declaration or statement expected.

503 export type { ElementPart };
    ~~~~~~
node_modules/gantt-schedule-timeline-calendar/node_modules/lit-html/lit-html.d.ts:503:13 - error TS1005: ';' expected.

503 export type { ElementPart };
                ~

** Angular Live Development Server is listening on localhost:5999, open your browser on http://localhost:5999/ **
ℹ ｢wdm｣: Failed to compile.
```

**Comment by neuronetio** [comment]
You should exclude node_modules from typescript in your ts configuration.
https://www.typescriptlang.org/tsconfig/skipLibCheck.html

`tsconfig.json`
```
{
  "compilerOptions": {
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by nsankar90** [comment]
Thanks for reverting back

but this only works for .ts files
all the errors are coming from .d.ts file 

I am also working on answers will post here if I got one or please post here once you find any 

Thanks

**Comment by neuronetio** [comment]
There are no errors in this repository, so maybe you are doing something differently?
Maybe you are importing something unnecessarily?

**Comment by neuronetio** [comment]
do you have `include` option in your project?
```
{
 "include":["src/**/*.ts"], // do you have something like this or similar?
 "exclude": ["node_modules"]
  "compilerOptions": {
    "skipLibCheck": true
  },

}
```
